### ISSUE TITLE
offst-crypto: Rename crypto_rand.rs to rand.rs

### ISSUE THREAD

**Issue by realcr** [freedomlayer/offst#210]
`crypto_rand.rs` is an unfortunate choice of name for the random utils module inside `offst-crypto` crate.

For example, this is what current imports look like:
```rust
use crypto::crypto_rand::{CryptoRandom, RandValue};
```

A better name for this module might be just `rand`, which should result in imports of this form:

```rust
use crypto::rand::{CryptoRandom, RandValue};
```

The crypto crate is used in most of offst crates. I suggest to begin with modifying the lowest crates first: `offst-common` and `offst-proto`, and only then move on to the rest of the crates.

At any time, running `cargo test` should show any failures during the renaming. The more specific `cargo test -p offst-XYZ` allows to test a specific crate (Given that all dependencies compile too).

This issue does not require great familiarity with the Offst project, and I think it can be solved by Rust beginners too. Guidance will be given to anyone who wants to solve this. Please send a message if you plan to work on this issue.

**Comment by Atul9** [comment]
@realcr I would like to take this up.

**Comment by realcr** [comment]
@Atul9 : Great! Welcome to the Offst project, and thank you for your help.
If you need any help with this issue don't hesitate to send a message.

**Comment by Atul9** [comment]
@realcr I have opened up a PR https://github.com/freedomlayer/offst/pull/212, please review.
