### ISSUE TITLE
serde_derive not required in 2018 edition

### ISSUE THREAD

**Issue by realcr** [freedomlayer/offst#232]
Some crates in the Offst codebase still use `serde_derive`. This is no longer required, see: 
https://www.reddit.com/r/rust/comments/a8ykj8/til_you_dont_need_serde_derive_when_using_the/

We should update all the crates to have `serde = { version = "1.0", features = ["derive"] }` instead in their Cargo.toml.

This issue can be solved by a beginner in Rust. Guidance can be given upon request.

**Comment by cyrtophora** [comment]
Hi, @realcr I would like to take this one.

**Comment by realcr** [comment]
@cyrtophora : Thank you for your contribution! If you need any help with this don't hesitate to send a message.

**Comment by realcr** [comment]
@cy6erlion : Thanks for the help! Closing this issue.
